scrape_configs:
  - job_name: animalbuttons-api
    metrics_path: /metrics
    static_configs:
      # Replace the port with the port your /metrics endpoint is running on
      - targets: ['fastapi-on-railway.railway.internal:8000']
    scrape_interval: 5000ms