scrape_configs:
  - job_name: animalbuttons-api
    metrics_path: /metrics
    static_configs:
      # Replace the port with the port your /metrics endpoint is running on
      - targets: ['https://python-fastapi-animals-production.up.railway.app']
    scrape_interval: 5s