scrape_configs:
  - job_name: animalbuttons-api
    metrics_path: /metrics
    static_configs:
      # Replace the port with the port your /metrics endpoint is running on
      - targets: ['python-fastapi-animals.railway.internal:8080']
    scrape_interval: 5s