scrape_configs:
  - job_name: animalbuttons-api
    metrics_path: /metrics
    static_configs:
      # Replace the port with the port your /metrics endpoint is running on
      - targets: ['python-fastapi-animals-production.up.railway.app']
    scrape_interval: 5s
  - job_name: autometrics-slack-app
    metrics_path: /metrics
    static_configs:
      - targets:
          - "autometrics-slack-app"

rule_files:
  - "/etc/prometheus/autometrics.rules.yml"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'railway-alertmanager.railway.internal' ]